import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <body
        style={{ display: "flex", flexDirection: "column", minHeight: "100%" }}
      >
        <Header />
        <link
          href="https://fonts.googleapis.com/css2?family=Playwrite+CO:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <main
          style={{
            flex: 1,
            paddingTop: "140px", // Lägger till en padding för att undvika att headern täcker page
          }}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
